- name: Checkout Deployment Repository
  uses: actions/checkout@v4
  with:
    repository: kjs0508/my_deploy # Replace with your GitHub username and repo name
    ref: main
    token: ${{ secrets.GH_TOKEN }}

- name: Update k8s Manifest
  env:
    DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
    DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
    IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
  run: |
    sed -i "s@image: .*/.*:.*@image: $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG@g" deployment.yml

- name: Commit and Push Changes
  env:
    GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
    GIT_NAME: ${{ secrets.GIT_NAME }}
  run: |
    git config user.email "$GIT_EMAIL"
    git config user.name "$GIT_NAME"
    git add deployment.yml
    git commit -m "Update image tag"
    git push origin main
